blank_issues_enabled: false
contact_links:
  - name: GitHub Discussion
    url: https://github.com/FrancoGiudans/Capsulyric/discussions
    about: Ask questions and get help from the community / 在此处提问并获取社区帮助
